apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-frontend
  labels:
    app: uda-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uda-frontend
  template:
    metadata:
      labels:
        app: uda-frontend
    spec:
      containers:
      - name: udagram-refactor-frontend
        image: mvrkrishna/udagram-refactor-frontend
        resources:
          limits:
            cpu: "1.5"
          requests:
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
