apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-frontend-1
  labels:
    app: udacity-frontend-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-frontend-1
  template:
    metadata:
      labels:
        app: udacity-frontend-1
    spec:
      containers:
      - name: udacity-frontend-1
        image: aronanubhav/udacity-frontend-1
        resources:
          limits:
            cpu: "1.5"
          requests:
            cpu: "500m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
