apiVersion: v1
kind: Service
metadata:
  labels:
    app: udacity-frontend-1
  name: udacity-frontend-1
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udacity-frontend-1
